### ISSUE TITLE
main doc links to 2.2.0 instead of recent 2.4.0

### ISSUE THREAD

**Issue by battlemidget** [canonical-docs/conjure-up-docs#23]
When clicking on https://docs.ubuntu.com/conjure-up/en/ it redirects to previous 2.2.0 version instead of the recently added 2.4.0

**Comment by evilnick** [comment]
Yes, I noticed that too. It is more of a web issue than a docs one, as I suspect, looking at the links, it is a redirect that needs changing, but I will look into it.

**Comment by evilnick** [comment]
this works now
