### ISSUE TITLE
make a stable version to always point to whatever release is newest

### ISSUE THREAD

**Issue by battlemidget** [canonical-docs/conjure-up-docs#29]
I am working on updating the documentation which will cover conjure-up 2.5.x. Is it possible to update the version links to be something like:

2.2.0 | 2.4.0 | 2.5.0 | stable | devel

Where stable -> 2.5.0 (whatever's latest)

**Comment by evilnick** [comment]
Hi, sure, we can certainly sort something out. I know @nottrobin isn't keen on some of the naming patterns and we don't have baked in support for this in documentation builder currently
https://github.com/canonical-webteam/documentation-builder/issues/81
however, we can at least set up some redirects

**Comment by battlemidget** [comment]
Honestly, we could remove the versions and just have stable/devel. Since switching to snap the releases are more frequent and makes it difficult to do the versioned docs this way.

**Comment by evilnick** [comment]
Okay, I have released various fixes to make this happen. Links to the old pages should redirect to current stable version.
At some point we may be able to make master == devel, but there are a few tooling tweaks needed to make that happen. We probably also want to make the current version prominent on the index page
